use_frameworks!

target 'LFYTextInputFilter_Example' do
  pod 'LFYTextInputFilter', :path => '../'
  pod 'IQKeyboardManager'

  target 'LFYTextInputFilter_Tests' do
    inherit! :search_paths

    
  end
end
